version: '3.8'
services:
  mongodb:
    image: mongo:7
    container_name: mongodb-cynova
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: 